export const STR = {
  title: "AMUNDI",
  subtitle: "New Hire: Day One",
  start: "PRESS SPACE / TAP TO START",
  score: "Knowledge Points",
  room_lobby: "Main Lobby",
  room_executive: "Executive Suite",
  room_marketing: "Marketing & Products",
  room_etf: "ETF & Technology",
  room_history: "History Room",
  interact: "[ E ] Interact",
  quiz_title: "Quick Challenge!",
  correct: "✓ Correct! Well done!",
  wrong: "✗ Not quite — here's the answer:",
  answer: "Select your answer:",
  dept_locked: "Collect more Knowledge Points to enter!",
  complete: "CONGRATULATIONS!",
  complete_sub: "You've explored Amundi HQ!",
  play_again: "Play Again",
  controls: "WASD / Arrows to move  |  E to interact",
  fact_label: "📌 Did you know?",
};
