export const STR = {
  title: "AMUNDI",
  tagline: "The Journey",
  sub: "A Global Discovery Experience",
  start: "BEGIN YOUR JOURNEY",
  complete: "JOURNEY COMPLETE!",
  discovered: "milestones discovered",
  replay: "Explore Again",
  surface: "← Surface  (Esc)",
  challenge: "🎯  Take the Challenge",
  done_badge: "✓  Challenge Completed",
  continue: "Continue →",
  hint_map: "Scroll / pinch to zoom  •  Click a node to dive in",
  hint_keys: "Press 1–4 to answer  •  Esc to surface",
  footer: "€2,398bn AUM  •  200M+ Clients  •  35+ Countries  •  Founded 2010",
};
